# Generated by Django 3.2.16 on 2022-11-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0003_auto_20221103_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='party_size',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
