# Generated by Django 3.2.16 on 2022-11-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0005_alter_reservation_party_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.IntegerField(error_messages={'invalid': 'Please enter a valid phone number'}),
        ),
    ]
